services:
  app:
    build:
      context: .
      dockerfile: Dockerfile
    container_name: n8n-submission-manager
    ports:
      - "5777:5173"
    # networks:
    #   - app-network
    healthcheck:
      test: ["CMD", "wget", "--spider", "http://localhost:5173"]
      interval: 10s
      timeout: 5s
      retries: 3

  # nginx:
  #   image: nginx:alpine
  #   container_name: nginx-proxy
  #   ports:
  #     - "80:80"
  #   volumes:
  #     - ./nginx.conf:/etc/nginx/conf.d/default.conf
  #   depends_on:
  #     app:
  #       condition: service_healthy
  #   networks:
  #     - app-network

# networks:
#   app-network:
#     driver: bridge